"""add player domain

Revision ID: 822b3933b928
Revises: 1a31ce608336
Create Date: 2025-10-07 18:14:32.004768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '822b3933b928'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_name'), 'division', ['name'], unique=True)
    op.create_table('divisiongroup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisiongroup_name'), 'divisiongroup', ['name'], unique=False)
    op.create_table('player',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['divisiongroup.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_index(op.f('ix_divisiongroup_name'), table_name='divisiongroup')
    op.drop_table('divisiongroup')
    op.drop_index(op.f('ix_division_name'), table_name='division')
    op.drop_table('division')
    # ### end Alembic commands ###
